name: React Native iOS Build

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  ios-build:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Install CocoaPods
        working-directory: ios
        run: pod install

      - name: Build iOS
        run: |
          xcodebuild \
            -workspace ios/MyRNApp.xcworkspace \
            -scheme MyRNApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath $PWD/build/MyRNApp.xcarchive \
            archive \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload iOS archive
        uses: actions/upload-artifact@v4
        with:
          name: MyRNApp-iOS-archive
          path: build/MyRNApp.xcarchive